server:
  port: 8080

server.servlet.encoding.force-response: true


spring:
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0

  session:
    store-type: redis

  datasource:
    url: jdbc:mysql://127.0.0.1/edusmile?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: '!eorlf123'


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB


  server:
    error:
      path: /error  # 오류 경로 설정
      whitelabel:
        enabled: false  # 기본 오류 페이지 비활성화